### ISSUE TITLE
Automating bio.tools update through the bio.tools API as a GitHub action

### ISSUE THREAD

**Issue by magnuspalmblad** [magnuspalmblad/shic#2]
Implement a GitHub action to run the script that automatically updates the bio.tools entry for shic.

**Comment by magnuspalmblad** [comment]
This is now partially implemented, as a "semi-automatic" update. Perhaps we could close the issue for now, as we may not wish to make it completely automatic, without a human in the loop?

**Comment by vedran-kasalica** [comment]
I completely agree!
